<?php
$this->pageHeader()->setTitle('Add Overtime Task');

$this->mainMenu()->setActiveItemId('task');

$this->pageBreadcrumbs()->setItems(
    [
        'Home'             => $this->url('home'),
        'Tasks'            => $this->url('tasks'),
        'Add Percent Task' => $this->url('task.percent', ['action' => 'add'])
    ]
);
?>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->formHelper($form) ?>
    </div>
</div>

