<?php
$this->headTitle('Add Task Percent');

$this->mainMenu()->setActiveItemId('task');

$this->pageBreadcrumbs()->setItems(
    [
        'Home'             => $this->url('home'),
        'Tasks'            => $this->url('tasks'),
        'Edit Percent Task' => $this->url('task.percent', ['action' => 'edit'])
    ]
);
?>

<h1>Add Percent Task</h1>


<div class="row">
    <div class="col-md-6">
        <?= $this->formHelper($form) ?>
    </div>
</div>

