<?php
$this->pageHeader()->setTitle('View User');

$this->mainMenu()->setActiveItemId('users');

?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <td class="text-strong">ID:</td>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            <tr>
                <td class="text-strong">E-mail:</td>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <td class="text-strong">Full Name:</td>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <td class="text-strong">Date Created:</td>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
            <tr>
                <td class="text-strong">Status:</td>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
            </tr>
        </table>
    </div>
</div>