<?php
$this->pageHeader()->setTitle('Инвестиции');

$this->mainMenu()->setActiveItemId('investments');

?>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Операция</th>
        <th>Дата</th>
        <th>Кол-во</th>
        <th>Курс</th>
        <th>Сумма инвестиций (руб.)</th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->items)) : ?>
        <?php foreach ($this->items as $item) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($item->getCode())?></td>
                <td><?php echo $this->escapeHtml($item->getname())?></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr><td colspan="5" class="text-center"><?= _('Инвестиции не найдены') ?></td></tr>
    <?php endif; ?>
    </tbody>
</table>
