<?php
/**
 * @var $date \DateTime
 * @var $exchange \Exchange\Entity\Exchange
 * @var $statusCrossAvg int
 * @var $taskFigureAnalyzes \Analysis\Entity\FigureAnalysis[]
 * @var $taskOvertimeAnalysis \Analysis\Entity\TaskOvertimeAnalysis
 * @var $taskPercentAnalyzes \Analysis\Entity\TaskOvertimeAnalysis[]
 */

if ($date) {
    echo '<h3>' . $exchange->getName() . ': Анализ  за ' . $date->format('d.m.Y') . '</h3>';
}

switch ($statusCrossAvg) {
    case \Analysis\Service\MovingAverage::STATUS_CROSS_UP:
        echo '<p><strong>' . _('РОСТ') . '.</strong> ' . _('Пересечение средней линии.') . '</p>';
        break;
    case \Analysis\Service\MovingAverage::STATUS_CROSS_DOWN:
        echo '<p><strong>' . _('ПАДЕНИЕ') . '.</strong> ' . _('Пересечение средней линии.') . '</p>';
        break;
}

echo '<div><img src="' . $this->serverUrl() . $srcGraph . '"/></div>';

/** @var \Analysis\Entity\FigureAnalysis $figure */
foreach ($taskFigureAnalyzes as $figure) {
    echo '<div>' . $this->figureAnalysis($figure) .  '</div>';
    echo '====================================<br /><br />';
}

if ($taskOvertimeAnalysis) {
    echo '<div>' . $this->overtimeAnalysis($taskOvertimeAnalysis) .  '</div>';
}

foreach ($taskPercentAnalyzes as $percent) {
    echo '<div>' . $this->percentAnalysis($percent) .  '</div>';
    echo '====================================<br /><br />';
}
