<strong>Module:</strong>        Exchange &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        Index


<h1>Список металов</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Код</th>
        <th>Наименование</th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->items)) : ?>
        <?php foreach ($this->items as $item) : ?>
            <tr>
                <td><?php echo (int)$item->getCode()?></td>
                <td><?php echo $this->escapeHtml($item->getname())?></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr><td colspan="2"><?php echo $this->notFound('Металы не найдены') ?></td></tr>
    <?php endif; ?>
    </tbody>
</table>