<?php
    $this->mainMenu()->setActiveItemId('course');
    echo $this->headerExchange($this->exchanges, $this->currentExchange, $this->period)
?>

<div id="chart_div"></div>

<?php
    $lisChart = array();
    $i = 0;
    foreach ($this->courses as $course) {
        $date = $course->getDate();
        $lisChart[] = '[new Date("' . $date->format('D M d Y') . '"),' . $course->getValue() . ',' . $this->movingAverage1[$i].']';
        $i++;
    }

    $this->headScript()->prependFile('https://www.gstatic.com/charts/loader.js');
    $this->headScript()->captureStart();
    echo "
    google.charts.load('current', {packages: ['corechart', 'line']});
    google.charts.setOnLoadCallback(drawBasic);
    
    function drawBasic() {
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'X');
        data.addColumn('number', 'course');
        data.addColumn('number', 'avg-1');
//        data.addColumn('number', 'avg-2');
//        data.addColumn('number', 'avg-3');
        data.addRows([" . implode(',', $lisChart) . "]);
        var options = {
            'height':500,
            'language': 'ru',
            hAxis: {
              title: 'Time'
            },
            vAxis: {
              title: '  '
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
    ";
    $this->headScript()->captureEnd();
?>
