<?php
    $this->mainMenu()->setActiveItemId('course');
    echo $this->headerExchange($this->exchanges, $this->currentExchange, $this->period);
?>

<?php
if ($this->currentExchange->isGold()) {
    echo '<div id="container" style="height: 400px; min-width: 310px"></div>';

    $this->headScript()->prependFile('https://code.jquery.com/jquery-3.1.1.min.js');
    $this->headScript()->prependFile('https://code.highcharts.com/stock/highstock.js');
    $this->headScript()->prependFile('https://code.highcharts.com/stock/modules/exporting.js');

    $this->headScript()->captureStart();
    echo "
                $.getJSON('" . $this->url('course-moex', ['id' => $this->currentExchange->getId()]) . "', function (data) {            
                    Highcharts.stockChart('container', {
                
                        rangeSelector: { selected: 1 },
                        title: { text: 'MOEX ".$this->currentExchange->getName()."' },
                
                        series: [{
                        name: '".$this->currentExchange->getShortName()."',
                            data: data,
                            type: 'area',
                            threshold: null,
                            tooltip: {
                            valueDecimals: 2
                            },
                            fillColor: {
                            linearGradient: {
                                x1: 0,
                                    y1: 0,
                                    x2: 0,
                                    y2: 1
                                },
                            stops: [
                                [0, Highcharts.getOptions().colors[0]],
                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                            ]
                            }
                        }]
                    });
                });";
    $this->headScript()->captureEnd();
}
?>
<hr>

<h3 class="text-center">Данные Центробанка</h3>
<div id="chart_div"></div>
<table class="table table-bordered">
    <?php
    $lisChart = [];
    $i = 0;
    foreach ($this->courses as $course) {
        $date = $course->getDate();
        echo '<tr>';
        echo '<td>' . $course->getDateFormatDMY() . '</td>';
        echo '<td>' . $this->formatMoney($course->getValue()) . '</td>';
        echo '</tr>';
//        $lisChart[] = '[new Date("' . $date->format('D M d Y') . '"),' . $course->getValue() . ',' . $this->movingAverage1[$i]. ']';
        $lisChart[] = '[new Date("' . $date->format('D M d Y') . '"),' . $course->getValue() . ',' . $this->movingAverage1[$i]. ',' . $this->movingAverage2[$i]. ']';
        $i++;
    }
    ?>
</table>

<?php
    $this->headScript()->prependFile('https://www.gstatic.com/charts/loader.js');
    $this->headScript()->captureStart();
    echo "
    google.charts.load('current', {packages: ['corechart', 'line']});
    google.charts.setOnLoadCallback(drawBasic);
    
    function drawBasic() {
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'X');
        data.addColumn('number', 'course');
        data.addColumn('number', 'avg-9');
        data.addColumn('number', 'avg-14');        
        data.addRows([" . implode(',', $lisChart) . "]);        
        var options = {
            'height':500,
            'language': 'ru',
            hAxis: {
              title: 'Time'
            },
            vAxis: {
              title: '  '
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
    ";
    $this->headScript()->captureEnd();
?>
