<?php
    $this->mainMenu()->setActiveItemId('course');
?>

<?php
    $this->headScript()->prependFile('https://code.jquery.com/jquery-3.1.1.min.js');
    $this->headScript()->prependFile('https://code.highcharts.com/stock/highstock.js');
    $this->headScript()->prependFile('https://code.highcharts.com/stock/modules/exporting.js');

    $this->headScript()->captureStart();
    echo "
        $.getJSON('" . $this->url('course-moex', ['id' => $this->currentExchange->getId()]) . "', function (data) {            
            Highcharts.stockChart('container', {
        
                rangeSelector: { selected: 1 },
                title: { text: 'MOEX акции ".$this->currentExchange->getName()."' },
        
                series: [{
                name: '".$this->currentExchange->getShortName()."',
                    data: data,
                    type: 'area',
                    threshold: null,
                    tooltip: {
                    valueDecimals: 2
                    },
                    fillColor: {
                    linearGradient: {
                        x1: 0,
                            y1: 0,
                            x2: 0,
                            y2: 1
                        },
                    stops: [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                    ]
                    }
                }]
            });
        });";
    $this->headScript()->captureEnd();

?>
<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#figure" aria-controls="figure" role="tab" data-toggle="tab">По фигурам</a></li>
        <li role="presentation"><a href="#maxday" aria-controls="maxday" role="tab" data-toggle="tab">Max By Day</a></li>
        <li role="presentation"><a href="#head-shoulders" aria-controls="head-shoulders" role="tab" data-toggle="tab">H&S</a></li>
        <li role="presentation"><a href="#three-bottom" aria-controls="three-bottom" role="tab" data-toggle="tab">3 Bottom</a></li>
        <li role="presentation"><a href="#double-bottom" aria-controls="double-bottom" role="tab" data-toggle="tab">2 Bottom</a></li>
        <li role="presentation"><a href="#revert-head-shoulders" aria-controls="revert-head-shoulders" role="tab" data-toggle="tab">revert H&S</a></li>
        <li role="presentation"><a href="#three-top" aria-controls="three-top" role="tab" data-toggle="tab">3 Top</a></li>
        <li role="presentation"><a href="#double-top" aria-controls="double-top" role="tab" data-toggle="tab">2 Top</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="figure">
            <div id="container" style="height: 400px; min-width: 310px"></div>
<?php
    echo '<div class="text-right">
            <a href="#" onclick="showAllAnalisys(); return false;">show all</a>
            <a href="' . $this->serverUrl(true) . '?refresh=true">обновить</a>
        </div>';
    foreach ($this->exchanges as $item) {
        if ($item['exchange']->getId() == $this->currentExchange->getId()) {
            echo $this->partial('course/index/partial/panel-analysis-stock', ['item' => $item]);
            break;
        }
    }
    echo $this->tableStock($this->exchanges);
?>
    </div>

        <div role="tabpanel" class="tab-pane" id="maxday">
            <?= $this->maxOneDayTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="three-bottom">
            <?= $this->threeBottomTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="three-top">
            <?= $this->threeTopTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="revert-head-shoulders">
            <?= $this->revertHeadShouldersTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="head-shoulders">
            <?= $this->headShouldersTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="double-bottom">
            <?= $this->doubleBottomTableStock($this->exchanges) ?>
        </div>

        <div role="tabpanel" class="tab-pane" id="double-top">
            <?= $this->doubleTopTableStock($this->exchanges) ?>
        </div>
    </div>
</div>